# Generated by Django 4.2.1 on 2023-12-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_property_is_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
